In [1]:
import pandas as pd
Trang = pd.read_csv("An (1).csv").drop(columns=["Unnamed: 0"])
Trang

,formula,geomean_profit,Value_limit,Geo_limit,Time_invest,Value_invest,Com_Invest,Profit_invest
0,+4*46*69,1.143167,0.027248,1.154444,48,0.244952,HQC,1.928571
1,+4*46*72,1.143167,0.020139,1.154444,48,0.146643,HQC,1.928571
2,+4*46*73,1.143167,0.020020,1.154444,48,0.148553,HQC,1.928571
3,+4*47*69,1.135763,0.027248,1.154444,48,0.244952,HQC,1.928571
4,+4*47*72,1.135763,0.020139,1.154444,48,0.146643,HQC,1.928571
...,...,...,...,...,...,...,...,...
965,-3-26-63,1.127053,-0.002237,1.127053,48,0.000000,NI,1.000000
966,-4-26-63,1.136377,-0.003154,1.140749,48,0.000000,NI,1.000000
967,-26-38-63,1.162184,-0.000041,1.168590,48,0.000000,LCM,0.870690
968,-36-43-63,1.133471,-0.001051,1.133471,48,0.000000,LCM,0.870690
969,-38-42-74,1.134559,-0.001950,1.152041,48,-0.000345,MSN,1.028571

In [7]:
from base import Method

vis = Method(pd.read_csv("Data_VietNam_File3.csv"), "Data_CT/", 20, "geomean")
Ann = vis.value_limit_filter(Trang, 1.0)
Ann

Các cột không được coi là biến: ['TIME', 'PROFIT', 'SYMBOL', 'EXCHANGE'].

,formula,geomean_profit,Value_limit,Geo_limit,Time_invest,Value_invest,Com_invest,Profit_invest
0,+4*46*69,1.143167,0.027248,1.154444,48,0.244952,HQC,1.928571
1,+4*46*72,1.143167,0.020139,1.154444,48,0.146643,HQC,1.928571
2,+4*46*73,1.143167,0.020020,1.154444,48,0.148553,HQC,1.928571
3,+4*47*69,1.135763,0.027248,1.154444,48,0.244952,HQC,1.928571
4,+4*47*72,1.135763,0.020139,1.154444,48,0.146643,HQC,1.928571
...,...,...,...,...,...,...,...,...
965,-3-26-63,1.127053,-0.002237,1.127053,48,0.000000,NI,1.000000
966,-4-26-63,1.136377,-0.003154,1.140749,48,0.000000,NI,1.000000
967,-26-38-63,1.162184,-0.000041,1.168590,48,0.000000,LCM,0.870690
968,-36-43-63,1.133471,-0.001051,1.133471,48,0.000000,LCM,0.870690
969,-38-42-74,1.134559,-0.001950,1.152041,48,-0.000345,MSN,1.028571