In [1]:
from base import Method
import pandas as pd
import numpy as np

vis = Method(pd.read_csv("Data_VietNam_File3.csv"), "Data/", 20)

Cảnh báo: Các cột không được coi là biến để sinh công thức: ['TIME', 'PROFIT', 'SYMBOL', 'EXCHANGE']. Nếu danh sách trên có một cột cần được coi là biến, hãy kiểm tra lại kiểu dữ liệu của cột.

In [ ]:
vis.find_threshold("+56*65-27")

In [ ]:
from scipy.stats import gmean
def Nguong(cong_thuc):
    Temp_ex = vis.explain_f(cong_thuc)

    temp_x= Temp_ex['Out_Value']
    # print(temp_x)
    Geo_Nguong = vis.get_formula_geomean_profit(cong_thuc)

    x_nguong = min(temp_x) - 10**(-10)
    # print('iii',Geo_Nguong,x_nguong)
    for x in temp_x:
        Geo_= []
        for i in range(0,len(Temp_ex['Out_Value'])):
            if Temp_ex['Out_Value'][i] > x:
                Geo_.append(Temp_ex['Out_profit'][i])
            else:
                Geo_.append(1.01)
        # print(gmean(Geo_),x)
        if gmean(Geo_) > Geo_Nguong:
            # print(gmean(Geo_),Geo_)
            Geo_Nguong = gmean(Geo_)
            x_nguong = x
        
        print(Geo_Nguong, x_nguong, x)

    return Geo_Nguong,x_nguong

Nguong("+56*65-27")

In [ ]:
vis.explain_formula("+56*65-27")

In [2]:
An = vis.xuat_file(pd.read_csv("An (1).csv")[["formula"]])
An

,formula,geomean_profit,Value_limit,Geo_limit,Time_invest,Value_invest,Com_invest,Profit_invest
0,+4*46*69,1.143167,0.027248,1.154444,48,0.244952,HQC,1.928571
1,+4*46*72,1.143167,0.020139,1.154444,48,0.146643,HQC,1.928571
2,+4*46*73,1.143167,0.020020,1.154444,48,0.148553,HQC,1.928571
3,+4*47*69,1.135763,0.027248,1.154444,48,0.244952,HQC,1.928571
4,+4*47*72,1.135763,0.020139,1.154444,48,0.146643,HQC,1.928571
...,...,...,...,...,...,...,...,...
965,-3-26-63,1.127053,-0.002237,1.127053,48,0.000000,NI,-1.000000
966,-4-26-63,1.136377,-0.003154,1.140749,48,0.000000,NI,-1.000000
967,-26-38-63,1.162184,-0.000041,1.168590,48,0.000000,LCM,0.870690
968,-36-43-63,1.133471,-0.001051,1.133471,48,0.000000,LCM,0.870690
969,-38-42-74,1.134559,-0.001950,1.152041,48,-0.000345,MSN,1.028571

In [3]:
Trang = pd.read_csv("An (1).csv").drop(columns=["Unnamed: 0"])
Trang

,formula,geomean_profit,Value_limit,Geo_limit,Time_invest,Value_invest,Com_Invest,Profit_invest
0,+4*46*69,1.143167,0.027248,1.154444,48,0.244952,HQC,1.928571
1,+4*46*72,1.143167,0.020139,1.154444,48,0.146643,HQC,1.928571
2,+4*46*73,1.143167,0.020020,1.154444,48,0.148553,HQC,1.928571
3,+4*47*69,1.135763,0.027248,1.154444,48,0.244952,HQC,1.928571
4,+4*47*72,1.135763,0.020139,1.154444,48,0.146643,HQC,1.928571
...,...,...,...,...,...,...,...,...
965,-3-26-63,1.127053,-0.002237,1.127053,48,0.000000,NI,1.000000
966,-4-26-63,1.136377,-0.003154,1.140749,48,0.000000,NI,1.000000
967,-26-38-63,1.162184,-0.000041,1.168590,48,0.000000,LCM,0.870690
968,-36-43-63,1.133471,-0.001051,1.133471,48,0.000000,LCM,0.870690
969,-38-42-74,1.134559,-0.001950,1.152041,48,-0.000345,MSN,1.028571

In [5]:
(An["Value_limit"] - Trang["Value_limit"]).abs().mean()

4.67983152802569e-11

In [ ]:
Trang[np.abs(An["Geo_limit"] - Trang["Geo_limit"]) >= 1e-10]

In [ ]:
import numpy as np
from numba import njit
@njit
def weighted_random(arr):
    """Trả ra index"""
    sum_ = np.sum(arr)
    if sum_ <= 1e-15:
        raise

    rand_ = np.random.uniform(0, sum_)

    for i in range(arr.shape[0]):
        rand_ -= arr[i]
        if rand_ <= 0:
            return i


from collections import Counter

In [ ]:
Counter(weighted_random(np.array([2, 1, 4, 3])) for i in range(1000000))